name: book-search

services:
  api:
    build: .
    environment:
      NODE_ENV: production
      PORT: 3000
      REDIS_URL: redis://redis:6379
      CACHE_TTL: 3600
    ports:
      - "3000:3000"
    depends_on:
      - redis
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data:
